version: '3'
services:
  redis:
    image: redis:alpine
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - redis
  counter:
    build: ./counter
    depends_on:
      - redis
  dashboard:
    build: ./dashboard
    ports:
      - "8080:8080"
    depends_on:
      - redis